[package]
name = "gallery"
version = "0.1.2"
edition = "2021"
description = "A static site generator for photo galleries"
keywords = ["static-site-generator", "photos", "gallery"]
categories = ["command-line-utilities", "template-engine"]
license = "MIT"
repository = "https://github.com/Christoph-D/gallery"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
handlebars = "4.4.0"
pulldown-cmark = { version = "0.9.3", default-features = false }
rayon = "1.8.0"
regex = "1.9.5"
serde = { version = "1.0.188", features = ["derive"] }
slug = "0.1.4"
time = { version = "0.3.28", features = ["macros", "parsing"] }

[dev-dependencies]
tempfile = "3.8.0"
