[package]
name = "gallery"
version = "0.1.2"
edition = "2021"
description = "A static site generator for photo galleries"
keywords = ["static-site-generator", "photos", "gallery"]
categories = ["command-line-utilities", "template-engine"]
license = "MIT"
repository = "https://github.com/Christoph-D/gallery"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
handlebars = "4.3.6"
pulldown-cmark = { version = "0.9.2", default-features = false }
rayon = "1.7.0"
regex = "1.8.1"
serde = { version = "1.0.162", features = ["derive"] }
slug = "0.1.4"
time = { version = "0.3.21", features = ["macros", "parsing"] }

[dev-dependencies]
tempfile = "3.5.0"
