[package]
name = "gallery"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
chrono = "0.4"
clap = "2.33.3"
handlebars = "4.1.1"
regex = "1"
serde = { version = "1.0.127", features = ["derive"] }
slug = "0.1.4"
rayon = "1.5.1"

[dev-dependencies]
tempfile = "3"
