[package]
name = "gallery"
version = "0.1.2"
edition = "2021"
description = "A static site generator for photo galleries"
keywords = ["static-site-generator", "photos", "gallery"]
categories = ["command-line-utilities", "template-engine"]
license = "MIT"
repository = "https://github.com/Christoph-D/gallery"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
handlebars = "4.3.6"
pulldown-cmark = { version = "0.9.2", default-features = false }
rayon = "1.6.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
slug = "0.1.4"
time = { version = "0.3.17", features = ["macros", "parsing"] }

[dev-dependencies]
tempfile = "3.3.0"
