[package]
name = "gallery"
version = "0.1.0"
edition = "2018"
description = "A static site generator for photo galleries"
keywords = ["static-site-generator", "photos", "gallery"]
categories = ["command-line-utilities", "template-engine"]
license = "MIT"
repository = "https://github.com/Christoph-D/gallery"

[dependencies]
anyhow = "1.0.42"
chrono = "0.4"
clap = { version = "3.1.6", features = ["derive"] }
handlebars = "4.1.1"
pulldown-cmark = { version = "0.8.0", default-features = false }
rayon = "1.5.1"
regex = "1"
serde = { version = "1.0.127", features = ["derive"] }
slug = "0.1.4"

[dev-dependencies]
tempfile = "3"
