[package]
name = "gallery"
version = "0.1.2"
edition = "2021"
description = "A static site generator for photo galleries"
keywords = ["static-site-generator", "photos", "gallery"]
categories = ["command-line-utilities", "template-engine"]
license = "MIT"
repository = "https://github.com/Christoph-D/gallery"

[dependencies]
anyhow = "1.0.78"
clap = { version = "4.4.12", features = ["derive"] }
handlebars = "5.0.0"
pulldown-cmark = { version = "0.10.0", default-features = false, features = ["html"] }
rayon = "1.8.0"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
slug = "0.1.5"
time = { version = "0.3.31", features = ["macros", "parsing"] }

[dev-dependencies]
tempfile = "3.9.0"
